const FETCHING_WORKSHOPS_LIST = 'FETCHING_WORKSHOPS_LIST';
const FETCHED_WORKSHOPS_LIST = 'FETCHED_WORKSHOPS_LIST';
const ERROR_FETCHING_WORKSHOPS_LIST = 'ERROR_FETCHING_WORKSHOPS_LIST';

export {
    FETCHING_WORKSHOPS_LIST,
    FETCHED_WORKSHOPS_LIST,
    ERROR_FETCHING_WORKSHOPS_LIST
};
